from enum import IntEnum
from typing import Callable, Any, TypedDict


class HTTPStatus(IntEnum):
    """
    Defines common HTTP status codes as an enumeration of integers.
    """

    OK = 200
    CREATED = 201
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    METHOD_NOT_ALLOWED = 405
    CONFLICT = 409
    INTERNAL_ERROR = 500
    RATE_LIMITED = 429

    @property
    def reason(self) -> str:
        """
        Returns a human-readable reason phrase for the status code.

        :returns: The status code name with underscores replaced by spaces.
        """
        return self.name.replace("_", " ")


# Standard HTTP end-of-line marker
END_OF_LINE = "\r\n"
# Directory where static files (HTML, CSS, JS) are stored
STATIC_DIR = "static"

# Common type hints for the server components


class RequestDictType(TypedDict):
    """
    Defines the structure of a parsed HTTP request dictionary.
    """

    method: str  # HTTP method (e.g., GET, POST)
    path: str  # Requested path (e.g., /api/user)
    query: dict[str, str]  # Query parameters
    headers: dict[str, str]  # Request headers
    body: str  # Request body content


class HTTPResponseType(TypedDict, total=False):
    """
    Defines the structure of a response dictionary generated by a handler.
    'total=False' means all fields are optional.
    """

    status: HTTPStatus  # The HTTP status code
    header: dict[str, Any]  # Response headers
    body: str  # Response body content (usually string or JSON string)


# Type for the function used by the handler to send the final response back to the client
SenderFunctionType = Callable[[HTTPResponseType], None]

HandlerFunctionType = Callable[[RequestDictType, SenderFunctionType], HTTPResponseType]
"""
Defines the type signature for all request handler functions.
Accepts a request dictionary and a sender function, and returns an HTTPResponseType dictionary.
"""
